name: camara_comunicaciones
description: Aplicación de cámara para Comunicaciones. Funciona con el Switcher Comunicaciones.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.9.41
  google_fonts: ^5.1.0
  provider: ^6.0.5
  go_router: ^10.1.2
  dart_frog: ^1.0.1
  web_socket_channel: ^2.4.0
  network_info_plus: ^4.0.2
  camera: ^0.10.5+4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/videos/